/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API information
         * @description Returns public API metadata without authentication.
         */
        get: operations["api_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events
         * @description Lists received monitoring events for the organization.
         */
        get: operations["events_list"];
        put?: never;
        /**
         * Submit monitoring events
         * @description Durably acknowledge a batch of 1–500 flow-monitoring events. Each event is validated independently; accepted and rejected indexes are returned together.
         */
        post: operations["events_ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an event
         * @description Returns one monitoring event by its event ID.
         */
        get: operations["events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get public health status
         * @description Returns a minimal public availability signal without exposing infrastructure details.
         */
        get: operations["health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List issues
         * @description Lists evidence-backed monitoring issues for the organization.
         */
        get: operations["issues_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/issues/{issue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an issue
         * @description Returns one monitoring issue by ID.
         */
        get: operations["issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Assign an issue
         * @description Assigns an issue to an organization member or unassigns it with null.
         */
        patch: operations["issues_assign"];
        trace?: never;
    };
    "/v2/issues/{issue_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List issue evidence
         * @description Lists events linked to an issue through its monitored operation.
         */
        get: operations["issues_list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/issues/{issue_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List issue notes
         * @description Lists append-only investigation notes for an issue.
         */
        get: operations["issues_list_notes"];
        put?: never;
        /**
         * Add an issue note
         * @description Adds an append-only investigation note to an issue. Repeat a request with the same Idempotency-Key to replay the original note.
         */
        post: operations["issues_add_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get organization
         * @description Returns the organization associated with the credential.
         */
        get: operations["organization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/organization/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organization members
         * @description Lists member IDs and roles who can be assigned to issues. Email addresses are not returned.
         */
        get: operations["organization_list_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIInfo: {
            /** @description Developer documentation URL. */
            documentation_url: string;
            /** @description API name. */
            name: string;
            /** @description Public service status URL. */
            status_url: string;
            /** @description Public API version. */
            version: string;
        };
        AddNoteRequest: {
            /** @description Append-only investigation note. */
            body: string;
        };
        Error: {
            /**
             * @description Stable machine-readable error code.
             * @enum {string}
             */
            code: "malformed_request" | "unauthorized" | "forbidden" | "request_too_large" | "invalid_input" | "not_found" | "idempotency_conflict" | "database_unavailable";
            /** @description Human-readable details about the request failure. */
            detail?: string;
            /** @description Short human-readable explanation. */
            message: string;
            /** @description HTTP status code for the problem. */
            status?: number;
            /** @description General category of the problem. */
            title?: string;
        };
        Event: {
            /** @description Normalized decimal amount, when present. */
            amount?: string | null;
            /** @description Three-letter ISO currency code, when present. */
            currency?: string | null;
            /** @description Target identifier derived from the event flow. */
            entity_id: string;
            /**
             * @description Target type derived from the event flow.
             * @enum {string}
             */
            entity_type: "wallet" | "order";
            /**
             * @description Lifecycle evidence type.
             * @enum {string}
             */
            event_type: "order.fulfilled" | "payment.failed" | "payment.initiated" | "payment.succeeded" | "payout.failed" | "payout.initiated" | "payout.succeeded" | "wallet.credited" | "wallet.debited" | "wallet.refunded";
            /**
             * @description Monitored money-movement flow.
             * @enum {string}
             */
            flow: "payment_to_wallet" | "payment_to_order" | "wallet_to_wallet" | "wallet_to_payout";
            /** @description Stable event identifier. */
            id: string;
            /**
             * Format: date-time
             * @description When the source event occurred.
             */
            occurred_at: string;
            /** @description Related provider name, when present. */
            provider?: string | null;
            /**
             * Format: date-time
             * @description When Reconify received the event.
             */
            received_at: string;
            /** @description Customer-supplied operation reference. */
            reference: string;
            /**
             * @description Asynchronous receipt processing state.
             * @enum {string}
             */
            status: "received" | "published" | "processed" | "failed";
        };
        Health: {
            /**
             * @description Public service availability status.
             * @enum {string}
             */
            status: "operational";
        };
        Issue: {
            /** @description User ID of the assigned organization member. */
            assigned_to?: string | null;
            /**
             * @description Deterministic reason the finding was raised.
             * @enum {string}
             */
            category: "business_failure" | "missing_event" | "mismatch" | "duplicate_or_conflict" | "data_quality";
            /** @description Stable issue identifier. */
            id: string;
            /** @description Evidence-backed explanation of the issue. */
            message: string;
            /**
             * Format: date-time
             * @description When the issue was opened.
             */
            opened_at: string;
            /** @description Related monitored operation identifier. */
            operation_id?: string | null;
            /**
             * Format: date-time
             * @description When the issue was resolved, if applicable.
             */
            resolved_at?: string | null;
            /**
             * @description Public severity classification.
             * @enum {string}
             */
            severity: "high" | "medium";
            /**
             * @description Current monitoring finding state.
             * @enum {string}
             */
            status: "open" | "resolved" | "resolved_late";
        };
        ListEventsResponse: {
            /** @description Events returned in descending occurred-at order. */
            events: components["schemas"]["Event"][];
            /** @description Page size used for this response. */
            limit: number;
            /** @description Opaque cursor for the next page, when available. */
            next_cursor?: string;
        };
        ListIssuesResponse: {
            /** @description Issues returned in descending opened-at order. */
            issues: components["schemas"]["Issue"][];
            /** @description Page size used for this response. */
            limit: number;
            /** @description Opaque cursor for the next page, when available. */
            next_cursor?: string;
        };
        ListMembersResponse: {
            /** @description Organization members. */
            members: components["schemas"]["Member"][];
        };
        ListNotesResponse: {
            /** @description Notes returned in chronological order. */
            notes: components["schemas"]["Note"][];
        };
        Member: {
            /** @description User identifier used for assignment. */
            id: string;
            /**
             * Format: date-time
             * @description When the member joined the organization.
             */
            joined_at: string;
            /**
             * @description Organization membership role.
             * @enum {string}
             */
            role: "owner" | "admin" | "analyst" | "viewer";
        };
        MonitoringBatchRequest: {
            /** @description One to 500 events to validate and ingest. */
            events: components["schemas"]["MonitoringEvent"][];
        };
        MonitoringBatchResponse: {
            /** @description Results in the same order as the submitted events. */
            results: components["schemas"]["MonitoringResult"][];
        };
        /** @description A monitoring event. Batches are limited to 500 events, requests to 5242880 bytes, and individual events to 262144 bytes. Amount and currency are required for all event types except payment.failed and payout.failed. entity_id identifies the target derived from the selected flow. */
        MonitoringEvent: {
            /** @description Decimal amount in the event currency. */
            amount?: string;
            /** @description Optional producer-supplied opaque identifier propagated across services. Do not include secrets or personal data. */
            correlation_id?: string;
            /** @description Three-letter uppercase ISO currency code. */
            currency?: string;
            /** @description Optional provider, failure, or retry context. */
            data?: components["schemas"]["MonitoringEventData"];
            /** @description Target identifier. Its entity type is derived from the selected flow. */
            entity_id: string;
            /**
             * @description Monitoring flow that defines the expected evidence sequence.
             * @enum {string}
             */
            flow: "payment_to_wallet" | "payment_to_order" | "wallet_to_wallet" | "wallet_to_payout";
            /** @description Optional stable ULID used to identify the event across retries. */
            id?: string;
            /** @description Optional flat key-value context retained with the event. */
            metadata?: {
                [key: string]: string | number | boolean;
            };
            /**
             * Format: date-time
             * @description Time when the event occurred in the source system.
             */
            occurred_at?: string;
            /** @description Stable local business reference supplied by the producer. */
            reference: string;
            /**
             * @description Lifecycle event type, such as payment.succeeded.
             * @enum {string}
             */
            type: "order.fulfilled" | "payment.failed" | "payment.initiated" | "payment.succeeded" | "payout.failed" | "payout.initiated" | "payout.succeeded" | "wallet.credited" | "wallet.debited" | "wallet.refunded";
        };
        MonitoringEventData: {
            /** @description Stable provider or source code for a failed event. */
            failure_code?: string;
            /** @description Human-readable failure context from the source system. */
            failure_message?: string;
            /** @description Opaque payment integration reference used for asynchronous provider tracking. */
            integration_ref?: string;
            /** @description Provider that originated or processed the event. */
            provider?: string;
            /** @description Provider-side identifier for the payment or payout. */
            provider_reference?: string;
            /** @description Provider transaction identifier. Numeric identifiers must be encoded as strings. */
            provider_transaction_id?: string;
            /** @description Whether the source considers the failed event retryable. */
            retryable?: boolean;
        };
        MonitoringResult: {
            /**
             * @description Stable machine-readable code for a rejected item.
             * @enum {string}
             */
            code?: "invalid_event" | "unknown_field" | "idempotency_conflict" | "duplicate" | "malformed_request";
            /** @description Reconify event identifier when the event was stored. */
            event_id?: string;
            /** @description Request field associated with the rejection. */
            field?: string;
            /** @description Zero-based position of the event in the request. */
            index: number;
            /** @description Short human-readable explanation. */
            message?: string;
            /**
             * @description Whether the event was accepted, duplicated, or rejected.
             * @enum {string}
             */
            status: "accepted" | "duplicate" | "rejected";
            /** @description Non-fatal normalization or validation warnings. */
            warnings?: string[];
        };
        MonitoringSchema: {
            error_codes?: ("invalid_event" | "unknown_field" | "idempotency_conflict" | "duplicate" | "malformed_request")[];
            limits?: {
                /** @constant */
                max_batch_events?: 500;
                /** @constant */
                max_event_bytes?: 262144;
                /** @constant */
                max_request_bytes?: 5242880;
            };
            warnings?: ("id_generated" | "occurred_at_generated")[];
        } & components["schemas"]["MonitoringEvent"];
        Note: {
            /** @description User who created the note, when available. */
            author_user_id?: string | null;
            /** @description Append-only investigation note. */
            body: string;
            /**
             * Format: date-time
             * @description When the note was created.
             */
            created_at: string;
            /** @description Stable note identifier. */
            id: string;
        };
        Organization: {
            /**
             * Format: date-time
             * @description When the organization was created.
             */
            created_at: string;
            /** @description Organization identifier. */
            id: string;
            /** @description Organization display name. */
            name: string;
            /** @description Organization URL slug. */
            slug: string;
        };
        /** @description Assignment update. Status transitions are not accepted by this version of the public API. */
        PatchIssueRequest: {
            /** @description Organization member ID to assign, or null to unassign. */
            assigned_to: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIInfo"];
                };
            };
        };
    };
    events_list: {
        parameters: {
            query?: {
                /** @description Number of records to return. */
                limit?: number;
                /** @description Opaque cursor returned by the previous response. */
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEventsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    events_ingest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitoringBatchRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringBatchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringBatchResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event identifier. */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    issues_list: {
        parameters: {
            query?: {
                /** @description Filter by finding status. */
                status?: "open" | "resolved" | "resolved_late";
                /** @description Number of records to return. */
                limit?: number;
                /** @description Opaque cursor returned by the previous response. */
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIssuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Issue identifier. */
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issues_assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Issue identifier. */
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchIssueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issues_list_events: {
        parameters: {
            query?: {
                /** @description Number of records to return. */
                limit?: number;
                /** @description Opaque cursor returned by the previous response. */
                after?: string;
            };
            header?: never;
            path: {
                /** @description Issue identifier. */
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEventsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issues_list_notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Issue identifier. */
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListNotesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issues_add_note: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional key for safe retries. The same key must represent the same issue and note body. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Issue identifier. */
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddNoteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    organization_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    organization_list_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMembersResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
